<a href="https://colab.research.google.com/github/Daffodilpearlzz/FMML/blob/main/Module_1_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

January 2022
Work completed and sessions attended: February 2022

Section 1
Python : Basic data types and indexing

In [ ]:
name='First Lab'
name_extended=name+' Module 1'
print(name_extended)

First Lab Module 1


In [ ]:
name_list = ['First Lab',3,'1.1','Lab 1']

In [ ]:
name_list.extend(['Module 1'])

In [ ]:
name_tuple = ('First Lab',1)

In [ ]:
set_unique = set([1,2,3,1,5,6,'Lab 1'])

In [ ]:
dic = {'1':'A','2':'B','C':3}
dic['4'] = 'New'

In [ ]:
print(name)
print(name_extended)
print(name_list)
print(name_tuple)
print(set_unique)
print(dic)

First Lab
First Lab Module 1
['First Lab', 3, '1.1', 'Lab 1']
('First Lab', 1)
{1, 2, 3, 5, 6, 'Lab 1'}
{'1': 'A', '2': 'B', 'C': 3, '4': 'New'}


In [ ]:
print(name[-1])
print(name[2])

print(name_tuple[-2])
print(name_tuple[0]) 

print(dic['1'])
print(dic['C'])

b
r
First Lab
First Lab
A
3


Section 2
Functions

In [ ]:
def add_new(a,b):
    sum = a + b
    return sum

ans = add_new(1,2)
print(ans)

def fn(a,b,c):
  func = a + (2*b) + (3*c)
  return func
answer = fn(3,67,92.69)
print(answer)

3
415.07


In [ ]:
def check_even_list(num_list):
  even_numbers = []
  for number in num_list:
    if number % 2 == 0:
      even_numbers.append(number)
    else:
      pass
  return even_numbers

output = check_even_list([1,2,3,4,5,6,7,8,9,10])
print(output)


[2, 4, 6, 8, 10]


In [ ]:
# Question 1 : 

# Given a list having Names, work_hours, and gender, Write a function to print name of the female worker that worked the most hours. Also how much do should she be paid if the pay is $ 20 per hour.

# work_hours = [('Abby',100 , 'F'),('Billy',400, 'M'),('Cassie',800,'F'), ('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]

def worker_list(wlist):
    max_name = ''
    max_salary = 0
    for e in wlist:
      if e[2] == 'F' and e[1] > max_salary:
        max_name = e[0]
        max_salary = e[1]
    print(max_name)
    print(max_salary*20)
    
work_hours = [('Abby',100,'F'),('Billy',400,'M'),('Cassie',800,'F'),('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]
worker_list(work_hours)



Penny
18400


Section 3 Libraries and Reading data

In [7]:
import numpy as np

In [8]:
a = np.array([1,1,2,3,4,5,5,6])
b = a>1
print(b)

[False False  True  True  True  True  True  True]


In [9]:
a = np.array([1,1,2,3,4,5,5,6])
b = a>1
print(a[b])

[2 3 4 5 5 6]


In [ ]:
a = np.array([1,1,2,3,4,5,5,6])
b = a>1
print(a[a>1])

[2 3 4 5 5 6]


In [ ]:
a_range = np.arange(10,19)
a_range

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [ ]:
a_range = np.arange(10,19).reshape(3,3)
a_range

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
a_range[0]

array([12, 15, 18])

In [ ]:
a_range[:,2]

array([12, 15, 18])

In [ ]:
iden = np.eye(3)
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
summed = a_range + iden
summed

array([[11., 11., 12.],
       [13., 15., 15.],
       [16., 17., 19.]])

In [ ]:
mul1 = a_range@iden
mul1

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])

In [ ]:
mul2 = a_range*iden
mul2

array([[10.,  0.,  0.],
       [ 0., 14.,  0.],
       [ 0.,  0., 18.]])

In [ ]:
mtx_a = a_range.T
mtx_a

array([[10, 13, 16],
       [11, 14, 17],
       [12, 15, 18]])

In [ ]:
mtx_1 = mul1.T
mtx_1

array([[10., 13., 16.],
       [11., 14., 17.],
       [12., 15., 18.]])

In [ ]:
mtx_2 = mul2.T
mtx_2

array([[10.,  0.,  0.],
       [ 0., 14.,  0.],
       [ 0.,  0., 18.]])

In [ ]:
mtx_1[(mtx_1 % 2 == 0)] = 0
mtx_1

array([[ 0., 13.,  0.],
       [11.,  0., 17.],
       [ 0., 15.,  0.]])

In [22]:
# Question 2 : 

# a)Create a 5x5 matrix of the following form, 

# [[1,1]
#  [2,2]]

#  i.e. each row is increasing and has repettiive elements.

#  Hint : you can use hstack, vstack  etc.
 
# b) find dot product of the matrix with any matrix. (Figure out the size/ shape of the matrix)

r1 = np.array([[1],[2],[3],[4],[5]])
matrix_req = np.hstack((r1,r1,r1,r1,r1))
print(matrix_req)

import random
random.random()
list = [random.randint(1,5) for i in range(25)]
len(list)
matrix_A = np.array([list]).reshape(5,5)
print(matrix_A)

dot_prdt = np.dot(matrix_req,matrix_A)
dot_prdt

[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]
[[2 5 2 5 3]
 [2 5 5 1 5]
 [2 2 1 4 1]
 [2 3 4 5 2]
 [4 2 5 3 3]]


array([[12, 17, 17, 18, 14],
       [24, 34, 34, 36, 28],
       [36, 51, 51, 54, 42],
       [48, 68, 68, 72, 56],
       [60, 85, 85, 90, 70]])

Reading files

In [23]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [24]:
with open ('/content/sample_data/README.md','r') as f:
  a = f.readlines()
a

['This directory includes a few sample datasets to get you started.\n',
 '\n',
 '*   `california_housing_data*.csv` is California housing data from the 1990 US\n',
 '    Census; more information is available at:\n',
 '    https://developers.google.com/machine-learning/crash-course/california-housing-data-description\n',
 '\n',
 '*   `mnist_*.csv` is a small sample of the\n',
 '    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is\n',
 '    described at: http://yann.lecun.com/exdb/mnist/\n',
 '\n',
 '*   `anscombe.json` contains a copy of\n',
 "    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it\n",
 '    was originally described in\n',
 '\n',
 "    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American\n",
 '    Statistician. 27 (1): 17-21. JSTOR 2682899.\n',
 '\n',
 '    and our copy was prepared by the\n',
 '    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c7315

In [25]:
import pandas as pd

df = pd.read_csv('/content/sample_data/california_housing_test.csv','r')
df.head(10)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only
  exec(code_obj, self.user_global_ns, self.user_ns)


longitude,"latitude","housing_median_age","total_  ...  ooms","population","households","median_income","median_house_value"
0  -122.050000,37.370000,27.000000,3885.000000,66...  ...                                                NaN                   
1  -118.300000,34.260000,43.000000,1510.000000,31...  ...                                                NaN                   
2  -117.810000,33.780000,27.000000,3589.000000,50...  ...                                                NaN                   
3  -118.360000,33.820000,28.000000,67.000000,15.0...  ...                                                NaN                   
4  -119.670000,36.330000,19.000000,1241.000000,24...  ...                                                NaN                   
5  -119.560000,36.510000,37.000000,1018.000000,21...  ...                                                NaN                   
6  -121.430000,38.630000,43.000000,1009.000000,22...  ...                                                NaN                   
7  -120.650000,35.480000,19.000000,2310.000000,47...  ...                                                NaN                   
8  -122.840000,38.400000,15.000000,3080.000000,61...  ...                                                NaN                   
9  -118.020000,34.080000,31.000000,2402.000000,63...  ...                                                NaN                   

[10 rows x 3 columns]